#All Events in the game. Chapter Title, Status, Description, Image
#If Adding a Translation Patch, change the titles here.
#Chapter 1
default prologue01 = CharacterEvent("A Fateful Night", status="not completed", desc= "A young man gets a second chance at life after a near-death accident." ,image="images/titles/prologue01title.webp")
default reinaevent01 =CharacterEvent("Welcome Home", status="not completed", desc= "Reina arrives to take the player to his new home.", image= "images/titles/reina01title.webp")
default camillaevent01 =CharacterEvent("A Nosy Next Door Neighbor", status= "not completed", desc="The player meets Camilla, a nosy but caring next door neighbor.",image="images/titles/camilla01title.webp")
default reinaevent02 =CharacterEvent("Meeting the Family",status="not completed",desc="The player meets Reina's family at her luxury mansion.", image="images/titles/reina02title.webp",)
default pennyevent01 =CharacterEvent("A Rebel with a Heart",status="not completed", desc="At Reina's request, the player visits Penny, a recluse girl with an eclectic taste in music.", image="images/titles/penny01title.webp")
default sabrinaevent01 =CharacterEvent("One Year Reunion",status="not completed",desc="The player reunites with Sabrina, his ex-girlfriend from a year prior.", image="images/titles/sabrina01title.webp")
default pennyevent02 =CharacterEvent("The Skater Girl", status="not completed",desc= "The player visits Penny at the skate park." , image="images/titles/penny02title.webp")
default brianaevent01 =CharacterEvent("The Knockout Queen",status="not completed", desc="The player visits Briana, a boxing champion contemplating her future.", image="images/titles/briana01title.webp")
default camillaevent02 =CharacterEvent("Helping Camilla Out", status = "not completed",desc="The player decides to help Camilla run her store.", image="images/titles/camilla02title.webp")
default jennievent01 =CharacterEvent("A Personal Bodyguard",status="not completed", desc="Jenni decides to take the player shopping with her.", image="images/titles/jenni01title.webp")
default jennievent02 =CharacterEvent("A Day at the Beach",status="not completed", desc= "After a day of shopping, Jenni takes the player to the beach to get to know him better.", image="images/titles/jenni02title.webp")
default brianaevent02 =CharacterEvent("A Big Announcement",status="not completed" , desc= "Briana announces her retirement from boxing to her family.", image="images/titles/briana02title.webp")
default epilogue01 = CharacterEvent("An Unexpected Visit", status="not completed", desc= "The player receives a visit with an unexpected visitor.", image="images/titles/epilogue01title.webp")

#Chapter 2
default prologue02 = CharacterEvent("The Morning After ", status="not completed", desc = "The player comes to terms with his past after the events of the previous night." ,image="images/titles/prologue02title.webp")
default reinaevent03 =CharacterEvent("Part Time Caregiver",status="not completed", desc="Reina takes care of the player while he recovers from his injuries." ,image="images/titles/reina03title.webp")
default jennievent03 =CharacterEvent ("Nurse Jenni",status="not completed", desc= "Jenni takes care of the player while he recovers from his injuries.", image="images/titles/jenni03title.webp")
default aishaevent01 =CharacterEvent("A Simple Investigation", status="not completed",desc="A police detective from Sierra City visits the player to ask a few questions.", image="images/titles/aisha01title.webp",)
default camillaevent03 =CharacterEvent("A Casual Check-in",status="not completed",desc= "Camilla visits the player after his recovery from the hospital", image="images/titles/camilla03title.webp")
default brianaevent03 =CharacterEvent("Briana's New Career",status="not completed", desc= "Briana talks with the player about her career after boxing.", image="images/titles/briana03title.webp")
default pennyevent03 =CharacterEvent("Penny's Dreams",status="not completed", desc = "Penny visits the player while he is recovering." ,image="images/titles/penny03title.webp")
default reinaevent04 =CharacterEvent("Reina's Breakdown",status="not completed", desc= "Reina breaks down during a quick checkup visit with Dr. Rose.", image="images/titles/reina04title.webp")
default brianaevent04 =CharacterEvent("Training Begins",status="not completed", desc= "Briana helps the player get in shape." , image="images/titles/briana04title.webp")
default pennyevent04 =CharacterEvent("A Wish Fulfilled", status="not completed", desc= "The player decides to help Penny with her dreams." ,image="images/titles/penny04title.webp")
default sabrinaevent02 =CharacterEvent("Like Old Times", status="not completed",desc="The player goes to Sabrina's apartment to have a little fun.", image="images/titles/sabrina02title.webp")
default jennievent04  =CharacterEvent ("Jenni's Secret",status="not completed", desc="The player discovers Jenni's secret life while at the beach.", image="images/titles/jenni04title.webp")
default epilogue02 = CharacterEvent("The Town Hall Meeting", status = "not completed",desc= "Jenni drags the player to an important Town Hall meeting, where he discovers a secret.", image = "images/titles/epilogue02title.webp")

#Chapter 3
default prologue03 = CharacterEvent("3 Months Later", status="not completed", desc= "Three months have passed and a body has been discovered in the Sierra River Basin.", image="images/titles/prologue03title.webp")
default reinaevent05 =CharacterEvent("A New Makeover",status="not completed", desc= "Reina gets a new makeover and a new personality.", image="images/titles/reina05title.webp")
default jennievent05  =CharacterEvent ("Crossing the Line",status="not completed", desc="Jenni asks for the player's help with moving out of the mansion.", image="images/titles/jenni05title.webp")
default miyukievent01 =CharacterEvent("The Political Campaign", status = "not completed",desc="The player decides to help Miyuki with her political campaign.",image="images/titles/miyuki01title.webp")
default camillaevent04 =CharacterEvent("Closing Sale", status="not completed", desc="The player helps Camilla on the last day of her shop.", image="images/titles/camilla04title.webp")
default aishaevent02 =CharacterEvent("Interrogation", status = "not completed",desc= "Aisha visits the player again after identifying the body in the river.", image="images/titles/aisha02title.webp")
default sabrinaevent03 = CharacterEvent("Sabrina's Forgiveness", status="not completed", desc= "Sabrina invites the player to her apartment to discuss her deceased cousin.", image="images/titles/sabrina03title.webp")
default brianaevent05 =CharacterEvent("The Big Debut", status="not completed", desc= "Briana makes her MMA debut.", image="images/titles/briana05title.webp")
default reinaevent06 =CharacterEvent("Meeting with the Divorce Lawyer",status="not completed", desc= "Reina meets with a divorce lawyer to discuss her options.", image="images/titles/reina06title.webp")
default reinaevent07 =CharacterEvent("Reina's Decision",status="not completed", desc= "Reina makes her decision regarding her marriage to Ethan", image="images/titles/reina07title.webp")

#Chapter 4
default reinaevent08 =CharacterEvent("A Changed Woman", status= "not completed", desc= "Reina reflects on the night before.", image="images/titles/reina08title.webp.")
default jennievent06 =CharacterEvent("Jenni's Desperation", status="not completed",desc= "Jenni tries to get closer to the player.", image="images/titles/jenni06title.webp")
default miyukievent02 =CharacterEvent("Corrupting Miyuki", status = "not completed",desc="The player discovers that Miyuki is a corrupt politician and uses it against her.",image="images/titles/miyuki02title.webp")
default camillaevent05 =CharacterEvent("Branching Paths", status="not completed", desc="Camilla contemplates over her next actions.", image="images/titles/camilla05title.webp")
default sabrinaevent04 = CharacterEvent("The Funeral", status="not completed", desc= "That player attends the funeral for Jane, Sabrina's cousin. ", image="images/titles/sabrina04title.webp")
default brianaevent06 =CharacterEvent("Training Resumes", status="not completed", desc= "The player and Briana resume training." ,image="images/titles/briana06title.webp")
default epilogue04 = CharacterEvent("Blackmailed",status="not completed",desc="The player receives an envelope full of compromising photos.", image="images/titles/epilogue04title.webp")

#Chapter 5
default prologue05 = CharacterEvent("Confronting the Drug Dealer", status="not completed", desc="The player decides to confront his former drug dealing friend.", image="images/titles/prologue05title.webp")
default brianaevent07 =CharacterEvent("The Main Event", status="not completed", desc= "On a winning streak, Briana goes up against a tougher opponent." ,image="images/titles/briana06title.webp")
default reinaevent09 =CharacterEvent("The Divorce Proceeding", status= "not completed", desc= "Reina goes through with the divorce.", image="images/titles/reina09title.webp.")
default jennievent07 =CharacterEvent("Jenni's Decision", status="not completed",desc= "Jenni decides to leave Sierra Beach for good.", image="images/titles/jenni07title.webp")
default pennyevent05 = CharacterEvent("Visiting Penny", status="not completed", desc= "The player visits Penny in the hospital.", image="images/titles/penny05title.webp")
default epilogue05 = CharacterEvent("Last Therapy Session", status="not completed", desc="The player visits Dr. Rose one last time.", image="images/titles/epilogue05title.webp")
#Epilogue
default epiloguestart= CharacterEvent("A Big Decision", status="not completed", desc="The player makes a decision to confront his problems or run away.", image="images/titles/epiloguestarttitle.webp")
default badending = CharacterEvent("Running Away From It All", status="not completed",desc="The player runs away from home, back to his former life.",image="images/titles/badendingtitle.webp")
default jenniending= CharacterEvent("Wish you were here",status="not completed",desc="The player moves to Spain with Jenni.", image="images/titles/jenniendingtitle.webp")
default pennyending= CharacterEvent("Indie debut",status="not completed",desc="The player helps Penny with her photography career.", image="images/titles/pennyendingtitle.webp")
default brianaending= CharacterEvent("A Hiking Trip",status="not completed",desc="The player helps Briana with the next phase of her life.", image="images/titles/brianaendingtitle.webp")
default reinaending= CharacterEvent("Starting Over",status="not completed",desc="The player starts an open relationship with Reina.", image="images/titles/reinaendingtitle.webp")
default sabrinaending= CharacterEvent("Newlyweds",status="not completed",desc="The player marries Sabrina and starts a new life.", image="images/titles/sabrinaendingtitle.webp")
default camillaending= CharacterEvent("A worldwind trip",status="not completed",desc="The player goes on a worldwide trip with Camilla.", image="images/titles/camillaendingtitle.webp")
default hiddenending = CharacterEvent("The King", status="not completed", desc="The player lives a carefree life, with women at his beck and call.", image="images/titles/kingendingtitle.webp")