#Chapter 1
image runningstart = Movie(play="videos/running.webm",side_mask=False)
image runningpov = Movie(play="videos/runningpov.webm", side_mask=False)
image sabrinaglow = Movie(play="videos/sabrinaglow.webm",side_mask=False)
image reinaglow = Movie(play="videos/reinaglow.webm",side_mask=False)
image reinamasturbation = Movie(play="videos/reinamast.webm", side_mask=False)
image dropdown = Movie(play="videos/dropdown.webm",side_mask=False)

#Chapter 2
image jennihandjob = Movie(play="videos/jennihandjob01.webm", side_mask=False)
image jenniblowjob01 = Movie(play="videos/jenniblowjob01.webm", side_mask=False)
image reinablowjob01 = Movie(play="videos/reinablowjob01.webm", side_mask=False)
image reinablowjob02 = Movie(play="videos/reinablowjob02.webm", side_mask=False)
image reinablowjob03 = Movie(play="videos/reinablowjob03.webm", side_mask=False)
image camillatitjob = Movie(play="videos/camillatitjob.webm", side_mask=False)
image camillariding01 = Movie(play="videos/camillariding01.webm", side_mask=False)
image camillariding02 = Movie(play="videos/camillariding02.webm", side_mask=False)
image sabrinablowjob01 = Movie(play="videos/sabrinablowjob01.webm",side_mask=False)
image sabrinablowjob02 = Movie(play="videos/sabrinablowjob02.webm",side_mask=False)
image sabrinahandjob01 = Movie(play="videos/sabrinahandjob01.webm",side_mask=False)
image sabrinafuck01 = Movie(play="videos/sabrinafuck01.webm",side_mask=False)
image sabrinafuck02 = Movie(play="videos/sabrinafuck02.webm",side_mask=False)


#Chapter 3
image miyukifuck01 = Movie(play="videos/Miyukifuck01.webm",side_mask=False)
image jenniblowjob02 = Movie(play="videos/jenniblowjob02.webm",side_mask=False)
image jenniriding01 = Movie(play="videos/jenniriding01.webm", side_mask=False)
image jenniriding02 = Movie(play="videos/jenniriding02.webm", side_mask=False)
image jenniriding03 = Movie(play="videos/jenniriding03.webm", side_mask=False)
image jenniriding04 = Movie(play="videos/jenniriding04.webm", side_mask=False)
image jenniriding05 = Movie(play="videos/jenniriding05.webm", side_mask=False)
image reinafireworks = Movie(play = "videos/reinafireworks.webm", side_mask=False)
image sabrinafuck03 = Movie(play="videos/sabrinafuck03.webm",side_mask=False)
image sabrinafuck04 = Movie(play="videos/sabrinafuck04.webm",side_mask=False)
image camillafuck01 = Movie(play="videos/camillafuck01.webm",side_mask=False)
image camillabj01 = Movie(play="videos/camillabj01.webm",side_mask=False)
image camillabj02 = Movie(play="videos/camillabj02.webm",side_mask=False)
image brianapromo = Movie(play= "videos/brianawalk.webm", side_mask=False)
image reinafuck01 = Movie(play ="videos/reinafuck01.webm", side_mask=False)
image reinafuck02 = Movie(play ="videos/reinafuck02.webm", side_mask=False)
image reinafuck03 = Movie(play ="videos/reinafuck03.webm", side_mask=False)
image reinafuck04 = Movie(play ="videos/reinafuck04.webm", side_mask=False)
image reinafuck05 = Movie(play ="videos/reinafuck05.webm", side_mask=False)
image reinanipples = Movie(play="videos/reinanipples.webm", side_mask=False)
image reinapussy01 = Movie(play="videos/reinapussy01.webm", side_mask=False)
image reinapussy02 = Movie(play="videos/reinapussy02.webm", side_mask=False)
image reinapussy03 = Movie(play="videos/reinapussy03.webm", side_mask=False)
image reinapussy04 = Movie(play="videos/reinapussy04.webm", side_mask=False)
image reinapussy05 = Movie(play="videos/reinapussy05.webm", side_mask=False)
image reinafuck06 = Movie(play="videos/reinafuck06.webm", side_mask=False)
image reinafuck07 = Movie(play="videos/reinafuck07.webm", side_mask=False)
image reinafuck08 = Movie(play="videos/reinafuck08.webm", side_mask=False)
image reinakiss = Movie(play="videos/reinakiss.webm",side_mask=False)
image reinablowjob05 = Movie(play="videos/reinablowjob05.webm",side_mask=False)
image sabrinafuck03 = Movie(play="videos/sabrinafuck03.webm",side_mask=False)

#Chapter 4
image reinafuck09 = Movie(play="videos/reinafuck09.webm", side_mask=False)
image reinafuck10 = Movie(play="videos/reinafuck10.webm", side_mask=False)
image reinafuck11 = Movie(play="videos/reinafuck11.webm", side_mask=False)
image reinafuck12 = Movie(play="videos/reinafuck12.webm", side_mask=False)
image reinablowjob04 = Movie(play="videos/reinablowjob04.webm",side_mask=False)
image jenniblowjob03 = Movie(play="videos/jenniblowjob03.webm", side_mask=False)
image jenniblowjob04 = Movie(play="videos/jenniblowjob04.webm", side_mask=False)
image jenniblowjob05 = Movie(play="videos/jenniblowjob05.webm", side_mask=False)
image jenniblowjob06 = Movie(play="videos/jenniblowjob06.webm", side_mask=False)
image jennititjob = Movie(play="videos/jennititjob.webm", side_mask=False)
image jennifuck01 = Movie(play="videos/jennifuck01.webm", side_mask=False)
image jennifuck02 = Movie(play="videos/jennifuck02.webm", side_mask=False)
image camillabj03 = Movie(play="videos/camillabj03.webm",side_mask=False)
image camillafuck02 = Movie(play="videos/camillafuck02.webm",side_mask=False)
image camillafuck03 = Movie(play="videos/camillafuck03.webm",side_mask=False)
image camillafuck04 = Movie(play="videos/camillafuck04.webm",side_mask=False)
image brianabj01= Movie(play="videos/brianabj01.webm",side_mask=False)
image brianaride01 = Movie(play="videos/brianaride01.webm", side_mask=False)
image brianaride02 = Movie(play="videos/brianaride02.webm", side_mask=False)
image brianaride03 = Movie(play="videos/brianaride03.webm", side_mask=False)
image miyukifuck02 =Movie(play="videos/miyukifuck02.webm",side_mask=False)
image miyukifuck03 =Movie(play="videos/miyukifuck03.webm",side_mask=False)
image miyukifuck04 =Movie(play="videos/miyukifuck04.webm",side_mask=False)
image miyukifuck05 =Movie(play="videos/miyukifuck05.webm",side_mask=False)
image sabrinafuck04 = Movie(play="videos/sabrinafuck04.webm",side_mask=False)
image sabrinafuck05 = Movie(play="videos/sabrinafuck05.webm",side_mask=False)

#Chapter 5
image jennifuck03 = Movie(play="videos/jennifuck03.webm", side_mask=False)
image jennifuck04 = Movie(play="videos/jennifuck04.webm", side_mask=False)
image jennifuck05 = Movie(play="videos/jennifuck05.webm", side_mask=False)


#Gallery Only
image reinafullvideo01 = Movie(play="videos/reinafullvideo01.webm", side_mask=False)
image reinafullvideo02 = Movie(play="videos/reinafullvideo02.webm", side_mask=False)
image reinafullvideo03 = Movie(play="videos/reinafullvideo03.webm", side_mask=False)
image jennifullvideo01= Movie(play="videos/jennifullvideo01.webm", side_mask= False)
image jennifullvideo02 = Movie(play="videos/jennifullvideo02.webm", side_mask= False)
image jennifullvideo03 = Movie(play="videos/jennifullvideo03.webm", side_mask= False)
image sabrinafullvideo01 = Movie(play="videos/sabrinafullvideo01.webm", side_mask= False)
image brianafullvideo01 = Movie(play="videos/brianafullvideo01.webm", side_mask= False)
image camillafullvideo01 = Movie(play="videos/camillafullvideo01.webm", side_mask= False)
image camillafullvideo02 = Movie(play="videos/camillafullvideo02.webm", side_mask= False)
image camillafullvideo03 = Movie(play="videos/camillafullvideo03.webm", side_mask= False)
image miyukifullvideo01 = Movie(play="videos/miyukifullvideo01.webm", side_mask= False)





