label pennyending:
    scene pennyending01
    penny "That's the last shot for the day."
    main "How did they turn out?"
    penny "Pretty good. Look."
    penny "They won't need much post-processing. Then I'll submit them to the contest."
    main "Wow, these are amazing. Good job, Penny."
    penny "Thanks, [player_name]."
    penny "When I saw those photos, I thought someone was going to break into the house and you know-"
    main "I won't let that happen. To you. Or anyone."
    penny "You're amazing."
    main "Is something wrong."
    penny "Are we ...together?"
    main "Like boyfriend and girlfriend?"
    penny "Yeah."
    main "We can be, if you want."
    penny "This is so awkward. I've never had a boyfriend or anything."
    main "We can take it slow. No rushing."
    penny "Are you sure?"
    main "Yeah."
    penny "We can just makeout? Cuddle? Nothing serious?"
    main "Unless you want to."
    penny "Maybe."
    penny "But not in the front seat."
    main "So the back?"
    penny "Yeah."
    main "Better?"
    penny "Much better."
    main "You're eager."
    penny "I want to make it special."
    main "No photos. Trust me."
    penny "Ok."
    "(Penny got treated for depression and takes photography classes.)"
    "(She still plays the guitar from time to time, even in front of Reina and Briana.)"
    "(Life is good for the two of us.)"
    scene black with fade
    show text "Happy At Least: End" with Pause (5)
    jump endingscreen
    